In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df=pd.read_csv('/content/cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

**One hot encoding using pandas**

In [22]:
pd.get_dummies(df,columns=['fuel','owner'] ,dtype=int) # #we are not doing on hot encoding on the brand because it has too many unique brands

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

K-1 One Hot Encoding

In [23]:
pd.get_dummies(df,columns=['fuel','owner'] ,drop_first=True) #we drop the first colulmn of the dummy of each fuel and owner

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# Generally we use sklearn

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [25]:
x_test.head()

       brand  km_driven    fuel         owner
6251    Ford      69000  Diesel  Second Owner
7139   Honda      40000  Petrol   First Owner
728   Nissan      25000  Petrol  Second Owner
5748    Tata      80000  Petrol   Third Owner
4097     Kia       5000  Diesel   First Owner

In [26]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [27]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()  #we always fit the training dataset and transform both training and test

In [28]:
x_test_new=ohe.transform(x_test[['fuel','owner']]).toarray()

In [29]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)) #combining both the values of the converted nomial categorical data with rest of the data

array([['Maruti', 5621, 0.0, ..., 0.0, 0.0, 0.0],
       ['Renault', 5000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 70000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 90000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 50000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Volkswagen', 70000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

# One Hot Encoding
For the top categorical columns

In [30]:
counts=df['brand'].value_counts()

In [31]:
df['brand'].nunique
thrshold=100 #cars with 100 cars

In [33]:
repl =counts[counts<=thrshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [35]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0